config/routes.rb
Rails.application.routes.draw do
  resources :hours
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hour.rb
class Hour < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def home
        @hours = Hour.all
    end
    
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  def index
    @hours = Hour.all
  end

  def show
  end

  def new
    @hour = Hour.new
  end

  def edit
  end

  def create
    @hour = Hour.new(sche_params)
    if @hour.save!
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @hour.update!(sche_params)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    if @hour.destroy!
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def find_sche
    
  end

  def sche_params
    params.require(:hour).permit(:mon_hour, :date, :memo)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/homes/index.html.erb
<a href = "projects/" >プロジェクト</a>
<a href = "hours/" >工数入力</a>

app/views/hours/edit.html.erb
<h1>Hours#edit</h1>
<p>Find me in app/views/hours/edit.html.erb</p>

app/views/hours/index.html.erb
<h1>Hours#index</h1>
<p>Find me in app/views/hours/index.html.erb</p>

<div class = 'container'>
    <div id="calendar">
    </div>
    <%= link_to  "New Schedule", new_hour_path %>
</div>

<% @hours.each do |hour| %>
    <%= hour.mon_hour %>
    <%= hour.date %>
    <%= hour.memo %>
<%end%>

app/views/hours/new.html.erb
<h1>Hours#new</h1>
<p>Find me in app/views/hours/new.html.erb</p>

<%= form_for (@hour) do |f| %>
    <%= f.number_field :mon_hour %>
    <%= f.date_field :date %>
    <%= f.text_area :memo %>
    <%= f.submit %>
<%end%>

app/views/hours/show.html.erb
<h1>Hours#show</h1>
<p>Find me in app/views/hours/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apportion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <a href ="/" >TOPへ戻る</a>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>Find me in app/views/projects/index.html.erb</p>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>